chore: DM support
consolelabs/mochi-bot pull request #240
Opened 2022-08-22 09:55 UTC by catngh

**What does this PR do?**

-  support command in DM for `bals` and `withdraw`

2022-08-22 10:17 UTC, trkhoi commented
fix lint

2022-08-22 15:22 UTC, anhnh12 requested changes

2022-08-22 15:22 UTC, anhnh12 commented on src/commands/defi/balances.ts
> +    if (msg.channel.type == "DM") {
===

2022-08-22 15:22 UTC, anhnh12 commented on src/commands/defi/balances.ts
> +    if (msg.channel.type == "DM") {
===

2022-08-22 15:22 UTC, anhnh12 commented on src/adapters/defi.ts
> +    if (
should create `InsufficientBalanceError` and throw that if error message includes "balance is not enough"
check `DiscordWalletTransferError.ts` for reference

2022-08-22 15:22 UTC, anhnh12 commented on src/commands/defi/withdraw.ts
> +  if (data.error.includes("balance is not enough")) {
should create `InsufficientBalanceError` and throw that if error message includes "balance is not enough"
check `DiscordWalletTransferError.ts` for reference

2022-08-23 03:21 UTC, trkhoi approved these changes

2022-08-23 04:45 UTC, anhnh12 approved these changes

2022-08-23 06:12 UTC, merged