refactor: update profile adapter to use fetcher
consolelabs/mochi-bot pull request #271
Opened 2022-08-30 10:33 UTC by phucledien

**What does this PR do?**

- [x] refactor the profile adapter to use Fetcher
- [x] remove unused code in the profile adapter

2022-08-30 15:38 UTC, anhnh12 approved these changes

2022-08-31 04:50 UTC, tuanddd requested changes

2022-08-31 04:50 UTC, tuanddd commented on src/adapters/profile.ts
>      )
```suggestion
    return await this.jsonFetch<UserProfileResponse>(
      `${API_BASE_URL}/profiles`, {
          query: {
              guildId,
              userId
          }
      }
    )
```

2022-08-31 04:50 UTC, tuanddd commented on src/adapters/profile.ts
> +    return await this.jsonFetch<GetUserNFTsResponse>(url)
```suggestion
    return await this.jsonFetch<GetUserNFTsResponse>(`${INDEXER_API_BASE_URL}/${userAddress}/nft`, {
        query: {
            page,
            size,
            collectionAddresses
        }
    })
```

Chỗ này ông nhớ sửa lại tên param `collectionAddress` -> `collectionAddresses` để có thể dùng shorthand property syntax của ES, với lại nếu `collectionAddresses` mà = undefined thì nó cũng sẽ tự động bị skip khi convert qua query string thôi nên không cần logic check if luôn

2022-08-31 04:50 UTC, tuanddd commented on src/adapters/profile.ts
> +    return await this.jsonFetch<GetUserNFTResponse>(url)
Bỏ hẳn string vào luôn không cần tạo biến `url` chi đâu

2022-08-31 04:50 UTC, tuanddd commented on src/adapters/profile.ts
>        `${API_BASE_URL}/users/gmstreak?discord_id=${discordId}&guild_id=${guildId}`
dùng cái `query` option mới nhé, ở dưới có ví dụ đó

2022-08-31 04:50 UTC, tuanddd commented on src/adapters/profile.ts
> +      `${API_BASE_URL}/profiles?guild_id=${guildId}&user_id=${userId}`
same

2022-08-31 04:50 UTC, tuanddd commented on src/adapters/profile.ts
> +      `${INDEXER_API_BASE_URL}/${userAddress}/collection?page=${page}&size=${size}`
same

2022-08-31 04:50 UTC, tuanddd commented on src/commands/profile/profile.ts
> +    throw new Error(userProfileResp.error)
Hạn chế throw error, thay vào đó return error embed bằng `getErrorEmbed` là dc rồi

2022-08-31 04:50 UTC, tuanddd commented on src/commands/profile/profile.ts
> +    throw new Error(userProfileResp.error)
này cũng v

2022-08-31 04:50 UTC, tuanddd commented on src/commands/profile/profile.ts
> +    throw new Error(userNftCollectionResp.error)
same

2022-08-31 04:50 UTC, tuanddd commented on src/commands/profile/profile.ts
> +    throw new Error(getUserNftResp.error)
Same

2022-08-31 04:50 UTC, tuanddd commented on src/commands/profile/profile.ts
> +    throw new Error(getNftDetailResp.error)
Same

2022-08-31 05:21 UTC, tuanddd approved these changes

2022-08-31 05:22 UTC, merged