feat: welcome msg
consolelabs/mochi-bot pull request #309
Opened 2022-09-12 09:43 UTC by catngh

**What does this PR do?**
- New commands to config welcome channel `/welcome info` and `/welcome set <channel>`
![image](https://user-images.githubusercontent.com/84314071/189623002-c704c036-6ace-49ab-b0ab-dd88f4479753.png)

- Bot greets new members to the guild
![image](https://user-images.githubusercontent.com/84314071/189620939-1cd38aaa-4c9f-4902-a100-d0c57dbc73fc.png)

2022-09-12 13:10 UTC, tuanddd commented on src/adapters/config.ts
> +    return json.data
```suggestion
    return await this.jsonFetch(
      `${API_BASE_URL}/configs/welcome`,
      {
          query: {
              guildId
           }
      }
    )
```

2022-09-12 13:11 UTC, tuanddd commented on src/adapters/config.ts
> +    }
```suggestion
    return this.jsonFetch(`${API_BASE_URL}/configs/welcome`, {
      method: "POST",
      body: JSON.stringify({
        guild_id,
        channel_id,
        welcome_message,
      }),
    })
```

2022-09-12 13:12 UTC, tuanddd commented on src/adapters/config.ts
> +    }
```suggestion
    return await this.jsonFetch(`${API_BASE_URL}/configs/welcome`, {
      method: "DELETE",
      body: JSON.stringify({
        guild_id,
      }),
    })
```

2022-09-12 13:16 UTC, tuanddd commented on src/commands/config/welcome_slash/info.ts
> +  const guild = await config.getCurrentWelcomeConfig(interaction.guild.id)
chỗ này chắc phải sửa lại do cái hàm `getCurrentWelcomeConfig` trả về khác rồi

2022-09-12 13:16 UTC, tuanddd commented on src/commands/config/welcome_slash/message.ts
> +  const currentWelcomeConfig = await config.getCurrentWelcomeConfig(
đây cũng v

2022-09-12 13:16 UTC, tuanddd commented on src/events/guildMemberAdd.ts
> +  const welcomeChannel = await config.getCurrentWelcomeConfig(member.guild.id)
đây cũng v

2022-09-12 13:19 UTC, tuanddd commented on src/events/guildMemberAdd.ts
> +  if (!chan) return
nên send message alert về channel vì admin server đã set channel rồi nhưng vì lí do gì đó (có thể là channel bị delete) mà không gửi message được => đây là case mà admin nên có action để xử lý nên phải có alert

2022-09-12 13:21 UTC, tuanddd commented on src/events/guildMemberAdd.ts
> +    description: (<string>welcomeChannel.welcome_message).replaceAll(
```suggestion
    description: welcomeChannel.welcome_message.replaceAll(
```

2022-09-12 13:21 UTC, tuanddd commented on src/events/guildMemberAdd.ts
> +    ;(<TextChannel>chan).send({ embeds: [embed] })
```suggestion
    chan.send({ embeds: [embed] })
```

2022-09-14 03:17 UTC, tuanddd requested changes

2022-09-14 03:17 UTC, tuanddd commented on src/commands/config/welcome_slash/set.ts
> +  ) {
có 1 hàm `parseDiscordToken`, em dùng hàm đó để check luôn nha, hàm đó sẽ check value đó là kiểu gì (emoji, channel, mention, etc...) và đồng thời extract cái id ra luôn

2022-09-14 03:17 UTC, tuanddd commented on src/commands/config/welcome_slash/set.ts
> +  if (!chan.isText)
```suggestion
  if (!chan.isText())
```

2022-09-14 03:36 UTC, tuanddd approved these changes

2022-09-14 06:21 UTC, trkhoi approved these changes

2022-09-14 06:40 UTC, merged