feat: prune
consolelabs/mochi-bot pull request #381
Opened 2022-09-21 10:23 UTC by catngh

**What does this PR do?**

- Command to purge inactive or users without a specific role
![image](https://user-images.githubusercontent.com/84314071/191480543-5f9de88a-7687-4c2e-a865-2489e51d0e54.png)
![image](https://user-images.githubusercontent.com/84314071/191480592-03310b12-8071-425b-bfab-288d91602977.png)
![image](https://user-images.githubusercontent.com/84314071/191480619-426f1a87-8cbe-4982-ba66-756456ed471f.png)
![image](https://user-images.githubusercontent.com/84314071/191480719-942d5920-a066-4220-bc06-fb42a6ecd1fc.png)

2022-09-21 10:46 UTC, tuanddd requested changes

2022-09-21 10:46 UTC, tuanddd commented on src/commands/community/prune/inactive.ts
> +      }
```suggestion
throw new GuildIdNotFound({ message: msg })
```
magic 🔮

2022-09-21 10:46 UTC, tuanddd commented on src/commands/community/prune/inactive.ts
> +  msg?.delete()
tại sao phải delete msg e? Nếu mà interaction k phải tới từ prune command thì msg đó có bị delete luôn không?

2022-09-21 10:46 UTC, tuanddd commented on src/commands/community/prune/without.ts
> +      }
```suggestion
throw new GuildIdNotFound({ message: msg })
```
magic 🔮

2022-09-21 10:46 UTC, tuanddd commented on src/commands/community/prune/without.ts
> +      }
```suggestion
throw new CommandError({ message: msg, description: 'Please enter a valid role' })
```
🧙🏻‍♂️

2022-09-21 10:46 UTC, tuanddd commented on src/commands/community/prune/inactive.ts
> +  })
```suggestion
  const pruned = await i.guild?.members.prune({
    days: 30,
    reason: Sorry to say this but you've been inactive for more than 30 days so we had to remove you from ${msg.guild.name}`,
  })
```
Friendlier Mochi 😉

2022-09-21 10:46 UTC, tuanddd commented on src/commands/community/prune/without.ts
> +  msg.delete()
cùng câu hỏi

2022-09-21 10:46 UTC, tuanddd commented on src/commands/community/prune/without.ts
> +    await mem.kick("Role not set")
same với ở trên, nên pick message nào friendly chút

2022-09-21 10:54 UTC, catngh commented on src/commands/community/prune/inactive.ts
> +  msg?.delete()
em muốn cho cái response sau khi nhấn button thì nó mất đi

2022-09-22 04:33 UTC, tuanddd commented on src/commands/community/prune/inactive.ts
> +  msg?.delete()
không cần đâu em, giữ lại đi em, mai mốt còn trace lại

2022-09-22 05:14 UTC, tuanddd approved these changes

2022-09-22 05:47 UTC, trkhoi approved these changes

2022-09-22 05:50 UTC, merged