fix: change not enough arg cmd to help cmd
consolelabs/mochi-bot pull request #394
Opened 2022-09-23 09:03 UTC by hoangharry

**What does this PR do?**

-   [x] Change not enough args cmd to help cmd. Such as $nr, $nr set, $gm will not alert and change to help message.

**Media (Loom or gif)**
Before (will have alert noti)
![Screen Shot 2022-09-23 at 15 47 34](https://user-images.githubusercontent.com/49946656/191924373-f2b2e606-23b0-4604-97b2-46208581cd9b.png)

After (will not alert when in case specified, will alert if missing args)
![Screen Shot 2022-09-23 at 15 48 28](https://user-images.githubusercontent.com/49946656/191924555-bb3b2526-e2d9-4274-ad05-94cd4f6170f1.png)

Still alert if it actually misses args
![Screen Shot 2022-09-23 at 15 48 44](https://user-images.githubusercontent.com/49946656/191924592-b483d6c4-8106-4b3b-a72d-2514ab066aeb.png)

2022-09-23 09:09 UTC, nguyennh4522 approved these changes

2022-09-23 15:40 UTC, tuanddd requested changes

2022-09-23 15:40 UTC, tuanddd commented on src/commands/index.ts
> +    )
```suggestion
  const shouldShowHelp = isAcceptableCmdToHelp(
      commandObject.command,
      commandObject.aliases ?? [],
      actionObject?.command ?? "",
      message.content
    );
  const valid =
    validateCommand(
      finalCmd,
      args,
      !!actionObject,
      isSpecificHelpCommand ?? false
    ) || shouldShowHelp
  if (shouldShowHelp)
```

2022-09-24 02:10 UTC, tuanddd approved these changes

2022-09-24 02:36 UTC, merged