chore: wrap response defi
consolelabs/mochi-bot pull request #430
Opened 2022-09-30 08:40 UTC by catngh

**What does this PR do?**

- Update `bals` response type

2022-09-30 08:52 UTC, trkhoi requested changes

2022-09-30 08:52 UTC, trkhoi commented on src/commands/defi/balances.ts
> +    const res = await Defi.discordWalletBalances(guildId, msg.author.id)
why not keep old one, we dont change api resp right ?

2022-09-30 09:27 UTC, trkhoi approved these changes

2022-09-30 11:04 UTC, tuanddd requested changes

2022-09-30 11:04 UTC, tuanddd commented on src/adapters/defi.ts
> +      `${API_BASE_URL}/defi/balances?guild_id=${guildId}&discord_id=${discordId}`
dùng option query thay vì để trong url đi em

2022-09-30 11:04 UTC, tuanddd commented on src/adapters/defi.ts
> +      throw new Error("Error while fetching user balances: " + json.error)
nếu không phải custom logic thì move ra ngoài nha, chỗ nào dùng method này thì handle chỗ đó

2022-10-01 03:41 UTC, tuanddd approved these changes

2022-10-01 03:55 UTC, merged