chore: rework rr
consolelabs/mochi-bot pull request #515
Opened 2022-10-25 10:52 UTC by catngh

**What does this PR do?**

- Changed `$rr set` and `$rr remove` argument from `message_id` to `message_link`
- Update `$prune` expected error
- Refactor `$rr list`

New argument
![image](https://user-images.githubusercontent.com/84314071/197754364-2b94906b-6070-4127-8c5a-969bc5020de8.png)

2022-10-25 11:09 UTC, tuanddd requested changes

2022-10-25 11:09 UTC, tuanddd commented on src/utils/common.ts
> +}
```suggestion
export function isDiscordMessageLink(url: string) {
  return /(http(s)?:\/\/.)?(www\.)?discord.com\/channels\/[0-9]*\/[0-9]*\/[0-9]*/g.test(url)
}
```

2022-10-25 11:09 UTC, tuanddd commented on src/commands/config/reactionRole/set.ts
> +      throw new CommandError({
use `APIError`

2022-10-25 11:09 UTC, tuanddd commented on src/commands/config/reactionRole/remove.ts
> +    const messageLink = args[2].slice(29).split("/") // guild_id/chan_id/msg_id
```suggestion
    const [guildId, channelId, messageId] = args[2].split("/").slice(-3)
```

2022-10-25 11:58 UTC, catngh commented on src/commands/community/prune/inactive.ts
> +      }
bữa a Huy kêu lỗi này là expected, throw thì nó sẽ alert với log lại

2022-10-25 14:45 UTC, trkhoi approved these changes

2022-10-26 02:55 UTC, tuanddd approved these changes

2022-10-26 02:58 UTC, merged